name: Clang Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check formatting with clang-format
        run: |
          # Find all .cpp and .h files and run clang-format in diff mode
          FILES=$(find . -regex '.*\.\(cpp\|h\)' -not -path "./build/*")
          clang-format --dry-run --Werror --style=file $FILES
